### ISSUE TITLE
update for blender 3.x

### ISSUE THREAD

**Issue by mond-cz** [ProtoxiDe22/Blender-csv-fcurve-importer#1]
Hi, 
sorry for interruption, I just found you as the author of version for 2.8 ... would you be interested (proud) for 3.x update?
Thank you for reply :)

BTW ... if you briefly check the script ... is it possible to set "Data path" (Copy Data Path/Paste) of material node?
[My tests failed](https://blender.stackexchange.com/questions/271821), I mean copy paste is not an issue, but fcurve is generated still as Action at object level not at Shader Nodetree level ... current limitation or a bug?
Thank you for any info.

**Comment by ProtoxiDe22** [comment]
I haven't used this script in years, and i have no idea how to upgrade this really.
As for the data path, kinda the same, i jad never used blender scripring before thos, i just followed the migration guide for plugins and updated some function calls, so unfortunately I don't know how to help

**Comment by mond-cz** [comment]
OK :) Thank you for such a quick response ... thanks for your fix years ago :)
